name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      - name: Build MkDocs
        run: |
          mkdocs build

      - name: Copy site to docs folder
        run: |
          rm -rf docs/*        # Hapus konten lama di folder docs
          cp -r site/* docs/   # Salin hasil build MkDocs ke folder docs

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Update MkDocs site" || echo "No changes to commit"
          git push https://$PAT_TOKEN@github.com/maulanaaghnii/maulanaaghnii.github.io.git
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        
        